baseURL: "https://ubermensch.is-a.dev/blog"
title: Ann Naser Nabil
copyright: "© [Ann Naser Nabil](https://github.com/AnnNaserNabil)"
theme: [hugo-PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: true
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true

pagination:
  disableAliases: false
  pagerSize: 10

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Find Me On
          url: https://bit.ly/m/Ubermensch

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Theme PaperMod

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Howdy"
    Content: >
      👋 Welcome to my blog!

      - **Here**  I write anything and everything I find usefull.

      - Feel free to navigate to the posts and read .

      - See you on the other side.

  socialIcons:
    - name: github
      title: My Github
      url: "https://github.com/AnnNaserNabil"
    - name: Discord
      title: Reach out to Discord
      url: "https://discordapp.com/users/aureliiuuss"
    - name: X
      title: I am on X/Twitter
      url: "https://x.com/ann_naser"
    - name: Facebook
      title: My Facebook
      url: "https://facebook.com/nabil.ann"

  editPost:
    URL: "https://discordapp.com/users/aureliiuuss"
    Text: "Suggest Changes"
    appendFilePath: true

  assets:
    disableHLJS: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
